# 配置端口
server:
  port: 8775

# 配置consul的请求路径和端口,并且配置5s检测一次状态
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        health-check-path: /health
        health-check-interval: 5s
        instance-id: service-consul
  application:
    name: service-consul

# 配置连接注册中心
eureka:
  instance:
      prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

# 配置日志打印
logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      mybatis: ERROR
  path: D:/temp/logs/consul.log
#  file: ./logs/consul.log