server:
  port: 8083

spring:
  profiles: peer2

eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8082/eureka/,http://localhost:8081/eureka/

logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      mybatis: ERROR
  path: D:/logs/server-one.log
#  file: ./logs/server-one.log